attributes:

  password:
    type: "password"
    weight: 10
    value: ""
    label: "Admin password"
    description: "Type ScaleIO Admin password"
    regex:
      source: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$'
      error: "You must provide a password with between 8 and 15 characters, one uppercase, and one number"

  gateway_password:
    type: "password"
    weight: 20
    value: ""
    label: "Gateway password"
    description: "Type a password for the gateway"
    regex:
      source: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$'
      error: "You must provide a password with between 8 and 15 characters, one uppercase, and one number"

#  ephemeral_storage:
#    type: "checkbox"
#    value: true
#    label: "Use ScaleIO as ephemeral storage."
#    description: "Configure OpenStack Nova to keep ephemeral volumes on ScaleIO."
#    weight: 30

#  image_storage:
#    type: "checkbox"
#    value: true
#    label: "Use ScaleIO as image storage."
#    description: "Configure OpenStack Glance and Nova to use ScaleIO as storage for VM images."
#    weight: 40
  
  protection_domain:
    type: "text"
    value: "default"
    label: "Protection domain name"
    description: "Name of protection domains to be created if absent."
    weight: 60
    regex:
        source: '^\w+$'

  storage_pools:
    type: "text"
    value: "default"
    label: "Storage pool names"
    description: "Name of storage pool to be created. Could be a coma separated list for splitting devices between them."
    weight: 70
    regex:
        source: '^\w+$'

  device_paths:
    type: "text"
    value: ""
    label: "Storage devices"
    description: "Coma separated list of devices, e.g. /dev/sdb,/dev/sdc."
    weight: 80
    regex:
      source: '^(/dev/[a-zA-Z0-9:-_/]+){1}((,){1}(?=/dev/[a-zA-Z0-9:-_/]+))*'
      error: 'List of path is incorrect'

  sds_on_controller:
    type: "checkbox"
    value: true
    label: "Controller as Storage"
    description: "Setup SDS-es on controller nodes."
    weight: 90
        
  version:
    type: "select"
    weight: 120
    value: "2.0"
    label: "Version"
    description: "Select the ScaleIO version you wish to install. The only version 2.0 is supported for now."
    values:
      - data: "2.0"
        label: "2.0"

